### ISSUE TITLE
Alert definition not removed from prometheus

### ISSUE THREAD

**Issue by maevyn11** [docker-flow/docker-flow-monitor#49]
I believe I'm seeing an issue where after removing the com.df.alert labels from a service and redeploying it, the alert was not removed correctly from Prometheus. 

I actually made the same change in a staging environment and a production environment, and in staging the alert was removed, but in production the alert remains defined in prometheus. I suspect this may be due to the alert being in a firing state in production while I performed the update of the service. 

Interestingly, I can see that the monitor swarm listener does not contain the alert definition in it's output at /v1/docker-flow-swarm-listener/get-services

Below is the service definition. The commented lines were in the original service definition, and I redeployed with them commented out, intending to remove the alert definition. 

  logspout:
    image: gliderlabs/logspout:v3.2.4
    networks:
      - logging
    environment:
      - SYSLOG_FORMAT=rfc3164
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: syslog://logstash:51415
    deploy:
      mode: global
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        # - com.df.alertName=memlimit
        # - com.df.alertIf=@service_mem_limit:0.85
        # - com.df.alertFor=30s
      resources:
        reservations:
          memory: 30M
        limits:
          memory: 75M

Wondering if this is known behavior, and how I should remove the alert rules from docker flow monitor in a case like this? 

Happy to provide any follow up info needed.

**Comment by vfarcic** [comment]
@maevyn11 Please let me know if you managed to test it with the latest tag and whether we can close this issue.

**Comment by maevyn11** [comment]
@vfarcic Sorry for the delay on this. Just had a chance to test this out thoroughly, and it looks like it worked!

With a service at 65% memory limit, I was able to set the memlimit down to .5, see the alert firing, and then set it back up to .85 and see the alert stop firing.
