### ISSUE TITLE
No Autoscaling when Memory threshold is reached

### ISSUE THREAD

**Issue by nsalhab** [docker-flow/docker-flow-monitor#54]
Hi,
I am following the tutorial about Auto-scaling:
https://monitor.dockerflow.com/auto-scaling/ 

In order to make it easier to test the autoscaling when memory is NOT sufficient:

I reconfigured the service "go-demo_main" as follows:
- decreased the limits to 25% which is the easiest way forward,
- Changed the threshold for scaled it in down to 1 and scale up to 5
- Update the alertFor to 1minute of waiting in order not to wait long.
![image](https://user-images.githubusercontent.com/39637456/40612795-3f6c0f72-627c-11e8-9309-2377654e8035.png)

This is visible also in monitor/alerts:
![image](https://user-images.githubusercontent.com/39637456/40612901-a86ef58e-627c-11e8-9245-d0242572b7b5.png)

I am observing the Docker stats
![image](https://user-images.githubusercontent.com/39637456/40612832-588a76b0-627c-11e8-8e43-e9369c012a09.png)

It reads MEM% is bigger than 30%  for the tasks of the service go-demo_main, the scenario that is supposed to trigger a SCALE-OUT

![image](https://user-images.githubusercontent.com/39637456/40612985-01c87ea2-627d-11e8-9e7a-4a04cd05a997.png)

However, after 1 minutes, no scale-out took place! 
![image](https://user-images.githubusercontent.com/39637456/40612998-0a0a839e-627d-11e8-8512-5f0678c5e7f8.png)

The number of tasks per service is still the same before and after the PERIOD:
![image](https://user-images.githubusercontent.com/39637456/40612975-f4b2def6-627c-11e8-8209-53621db93073.png)

Below are some details:$ docker service  inspect go-demo_main  --pretty  | grep "com.df"

com.df.alertFor.1=5m    <----
com.df.alertIf.1=@service_mem_limit:0.1    <----
...
com.df.scaleMin=1    <----
com.df.scrapePort=8080com.df.servicePath=/demo

LOGS Are clean. No exception is seen:
Just reading:
***************************************
GET request to /demo/hello
***************************************

For the Resources:  
Resources:  
Reservations:    
Memory:    4MiB  
Limits:    
Memory:    20MiB

**Comment by thomasjpfan** [comment]
@nsalhab  You are missing the `cadvisor` exporter. The `container_memory_usage_bytes` metric is provided by the cadvisor exporter. You can see how to run the exporter by consulting https://monitor.dockerflow.com/tutorial/#collecting-metrics-and-defining-alerts.

After skimming the https://monitor.dockerflow.com/auto-scaling/ tutorial, I can see how this fact can be missed.
