### ISSUE TITLE
update prometheus version

### ISSUE THREAD

**Issue by dorsanyvision** [docker-flow/docker-flow-monitor#59]
Please update the version of prometheus in [Dockerfile](https://github.com/docker-flow/docker-flow-monitor/blob/master/Dockerfile) to v2.3.2 or at least something newer.

all versions are here:
https://hub.docker.com/r/prom/prometheus/tags/

**Comment by vfarcic** [comment]
Can you make a PR?

**Comment by dorsanyvision** [comment]
sure
PR: https://github.com/docker-flow/docker-flow-monitor/pull/60
