### ISSUE TITLE
Jenkins doesn't go on internet

### ISSUE THREAD

**Issue by alex-cloud-bit** [docker-flow/docker-flow-monitor#71]
Hi,
Jenkins jobs fails since they can't resolve any host, while the VirtualBox is correctly connected.
Could you add some configuration in the tutorial or describe here how to have the dockerized Jenkins already configured to go on internet?

I have already tried [this](https://stackoverflow.com/a/17004169/3673430), but it didn't work (I was already logged in)
```
docker@swadocker@swarm-1:~$ cat /etc/resolv.conf                                                                                                                 
nameserver 10.0.2.3

docker@swarm-1:~$ sudo sysctl -w net.ipv4.ip_forward=1
net.ipv4.ip_forward = 1
                                                                                                                                 
docker@swarm-1:~$ docker run busybox nslookup google.com 
Server:		10.0.2.3
Address:	10.0.2.3:53

Non-authoritative answer:
Name:	google.com
Address: 216.58.205.174

*** Can't find google.com: No answer

```

```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
swarm-1   *        virtualbox   Running   tcp://192.168.99.102:2376           v19.03.1   
swarm-2   -        virtualbox   Running   tcp://192.168.99.103:2376           v19.03.1  


# From the virtual machine:
docker@swarm-1:~$ ping github.com                                                                                                                      
PING github.com (140.82.118.4): 56 data bytes
64 bytes from 140.82.118.4: seq=0 ttl=63 time=44.182 ms
64 bytes from 140.82.118.4: seq=1 ttl=63 time=43.573 ms
^C
--- github.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 43.573/43.877/44.182 ms


docker@swarm-1:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:0F:84:20:53  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

docker_gwbridge Link encap:Ethernet  HWaddr 02:42:19:07:CB:74  
          inet addr:172.18.0.1  Bcast:172.18.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:19ff:fe07:cb74/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5943 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9786 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2499747 (2.3 MiB)  TX bytes:3000996 (2.8 MiB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:99:2E:5E  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe99:2e5e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:622257 errors:0 dropped:0 overruns:0 frame:0
          TX packets:186322 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:634018464 (604.6 MiB)  TX bytes:11836469 (11.2 MiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:A1:B9:57  
          inet addr:192.168.99.102  Bcast:192.168.99.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fea1:b957/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:912367 errors:0 dropped:0 overruns:0 frame:0
          TX packets:833600 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:350365461 (334.1 MiB)  TX bytes:313476366 (298.9 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

veth24750a5 Link encap:Ethernet  HWaddr CA:F2:29:12:DA:2B  
          inet6 addr: fe80::c8f2:29ff:fe12:da2b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5914 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9776 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2580960 (2.4 MiB)  TX bytes:3000421 (2.8 MiB)

veth39634b3 Link encap:Ethernet  HWaddr 32:73:8C:15:9E:2D  
          inet6 addr: fe80::3073:8cff:fe15:9e2d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:44 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:3008 (2.9 KiB)

veth98e43dd Link encap:Ethernet  HWaddr 0A:4F:F3:F5:85:40  
          inet6 addr: fe80::84f:f3ff:fef5:8540/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:27 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:1874 (1.8 KiB)

vetha8e3b37 Link encap:Ethernet  HWaddr BE:46:29:7C:F3:08  
          inet6 addr: fe80::bc46:29ff:fe7c:f308/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:2224 (2.1 KiB)

vethbe4c7e3 Link encap:Ethernet  HWaddr 4A:4F:CE:78:FD:08  
          inet6 addr: fe80::484f:ceff:fe78:fd08/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:41 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:2826 (2.7 KiB)

vethd6473cb Link encap:Ethernet  HWaddr D2:8E:83:A6:B2:DA  
          inet6 addr: fe80::d08e:83ff:fea6:b2da/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:33 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:2294 (2.2 KiB)

vethd8a0383 Link encap:Ethernet  HWaddr 8A:12:3A:D0:71:7A  
          inet6 addr: fe80::8812:3aff:fed0:717a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:42 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:2896 (2.8 KiB)

vethd8a649c Link encap:Ethernet  HWaddr 0A:0A:0E:DA:A4:C1  
          inet6 addr: fe80::80a:eff:feda:a4c1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:29 errors:0 dropped:0 overruns:0 frame:0
          TX packets:73 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1989 (1.9 KiB)  TX bytes:4989 (4.8 KiB)

```
![Screenshot from 2019-08-31 12-23-46](https://user-images.githubusercontent.com/54740742/64063060-65f9c200-cbef-11e9-8fb1-2af466303eeb.png)

**Comment by vfarcic** [comment]
Normally, that should work and there is probably something (e.g., proxy, VPN, etc.) in your network that blocks resolution of public domains. It's not uncommon that VMs are whitelisted but, since the process is running inside containers, whatever is blocking does not recognize it as being whitelisted. Then again, your problem might be something completely different but, in any case, it is most likely specific to your setup/network.

Can you enter inside the container by executing `docker container exec ... sh`? Once you're inside, please ping GitHub.com. I suspect that it will not be resolvable. If it isn't, please confirm that you can ping GitHub.com using its IP. If only the IP works, you should probably add `extra_hosts` to your Docker Compose YAML. You can find more info about it in https://docs.docker.com/compose/compose-file.

**Comment by alex-cloud-bit** [comment]
Hi, 
thanks for the answer, but as far as I know I have no proxy or firewall in place.
Everything works fine but the Jenkins settings, could it be done with a vanilla official Jenkins image?

Is there any command I could show you to let you understand the issue?

I have no output from the docker container exec command, could you give some extra detail please?

```
$ docker-machine ssh swarm-1
   ( '>')
  /) TC (\   Core is distributed with ABSOLUTELY NO WARRANTY.
 (/-_--_-\)           www.tinycorelinux.net

docker@swarm-1:~$ docker container exec 
exporter_cadvisor.x0je97i0mma4wv2wj91yldw1a.v5ubsn5w3smwqev1vxjom53x3
exporter_node-exporter.x0je97i0mma4wv2wj91yldw1a.l0wd9wdlhxl41au60jbapetl9
monitor_alert-manager.1.jo6rwkgwchdsveinjv7g847mg
monitor_monitor.1.tg5tt7mimg0f64r6icn3mxzsf
phoenix_app.1.1gj07j42hxmdr4zs51moo07ae
phoenix_mongo_app.1.ns5mull41jv8gdrhuta42inj8
proxy_swarm-listener.1.paxmly3kkp1liuz71bmxlq3j1
docker@swarm-1:~$ docker container exec monitor_alert-manager.1.jo6rwkgwchdsveinjv7g847mg sh 
docker@swarm-1:~$ docker container exec -i monitor_monitor.1.tg5tt7mimg0f64r6icn3mxzsf sh      
```

**Comment by vfarcic** [comment]
I'm a bit confused... Is the problem in Jenkins (as in the screenshot) or in Docker Flow Monitor (as in the last message)?

> Everything works fine but the Jenkins settings, could it be done with a vanilla official Jenkins image?

The problem does not seem to be related to Jenkins configuration, but that containers running in your cluster cannot resolve github.com. I'd bet that it's not resolvable not only inside the container that runs Jenkins but any other container inside the cluster. If I'm right, the issue can probably be solved by adding `extra_hosts` to your Docker Compose file.

We can organize a screen-sharing session in which I'd guide you and you will probably be able to explain better what the problem is. I'm available only on Monday next week (I'll be traveling after that). Does that sound OK?

**Comment by alex-cloud-bit** [comment]
I'm sorry for the confusion, I'm still understanding the architecture I built up starting from [this tutorial](https://monitor.dockerflow.com/auto-scaling/).

The problem could be also the Docker Flow Monitor since my integration with Slack hook works fine (alert_manager_config) but when I click on the link from the Slack channel i get a 503 on http://192.168.99.102/monitor/alerts : Docker Flow Proxy: _503 Service Unavailable,  No server is available to handle this request_. 

What I can tell you is that the connection from inside the Virtualbox VM to internet works, see screenshot below. 
I'm into how to use `extra_hosts` as you suggest, thanks.

If you mean this Monday 02 Sept I'd be happy to schedule a Zoom, otherwise we can reschedule it or just share the issue here. Anyway the offer is really kind.

![image](https://user-images.githubusercontent.com/54740742/64068792-7c2e6f00-cc3d-11e9-9fdb-cc972c844566.png)

**Comment by alex-cloud-bit** [comment]
Hi
I would like to add I tested the connection from inside a curl container and it works without --add-host.
So I think the problem is inside that Jenkins image configuration.
If it's not, how can I add add-host functionality directly inside the swarm yml?

`docker run --rm=True appropriate/curl -I https://github.com`
![image](https://user-images.githubusercontent.com/54740742/64097465-9ca51900-cd64-11e9-86e1-98bae597f36b.png)

**Comment by tuxerrante** [comment]
Hi
I'm try to investigate the same issue.
What I'm doing is

- Searching for errors inside those config files
I would point at this two lines in your output:
`proxy_proxy.1.aoeuwxvvxo6p@swarm-2    | [ALERT] 242/095837 (5644) : parsing [/cfg/haproxy.cfg:67] : 'server monitor_monitor' unknown keyword 'http'. Registered keywords :`

`proxy_proxy.1.aoeuwxvvxo6p@swarm-2    | [ALERT] 242/095837 (5644) : Parsing [/cfg/haproxy.cfg:72]: backend 'monitor_monitor-be9090_0' has the same name as backend 'monitor_monitor-be9090_0' declared at /cfg/haproxy.cfg:64.`
```
docker-machine ssh swarm-2
sudo find / -type f -name haproxy.cfg     
sudo find / -type f -name haproxy.cfg -exec grep -l "monitor_monitor-be9090_0" {} \; 
```
[HERE](https://cbonte.github.io/haproxy-dconv/1.8/intro.html) you can find the docs for haproxy
[HERE](https://discourse.haproxy.org/t/haproxy-not-starting-with-ssl-configuration/2330/7) a similar solved problem

Check also your [exporters.yml](https://github.com/docker-flow/docker-flow-monitor/blob/master/stacks/exporters.yml) where the haproxy image is loaded from.

**Comment by vfarcic** [comment]
@alex-cloud-bit You'll have to change your config to use shared libraries that you can access if public GitHub is unaccessible.

**Comment by tuxerrante** [comment]
I finally fixed the Jenkins docker connectivity issue.
It seems in the docker-flow-monitor [jenkins-scale.yml](https://github.com/docker-flow/docker-flow-monitor/blob/master/stacks/jenkins-scale.yml) file there was a wrong a definition of the default network, I replaced these lines:
```
  default:
    external: false
```
with
```
  monitor:
    external: true
```
Also there is a minor fix that should be done in the tutorial: the JSON path for labels actually is inspectJson[0].Spec.TaskTemplate.ContainerSpec.Labels["com.df.scaleMax"] and not inspectJson[0].Spec.Labels["com.df.scaleMin"].

It was also very helpful to put exporters and monitors in the same docker file.
Now I'm able to invoke the auto-scale job which works as expected. :)

Last step will be to fix the proxy, right now I have opened a port for every deployed image, I'm not able to access ${swarm-1 ip}/metrics .

**Comment by vfarcic** [comment]
Can you make a PR with the fixes?

**Comment by tuxerrante** [comment]
I'll be happy to do it, but I'd prefer to have a code review by you first, to be sure my configuration makes sense for your project too.
Then I'd like to ask you some indications for the right way to open the PR.
Thanks

**Comment by vfarcic** [comment]
The project does not have any specific (rigid) PR guidelines. Fork the repo, create a branch, make the changes to the code and push them to your branch, create a PR. From there on, I can review and offer suggestions. Don't worry if the PR is not fully finished. The important thing is to create it so that we can discuss the changes.

**Comment by vfarcic** [comment]
@tuxerrante Before you dive into creating a PR, I must warn you that there's not much movement in the project. Most users moved from Swarm to Kubernetes (including me).

What I'm really trying to say is that this project is looking for adoption; someone who uses Swarm and wants to take care of the project.

**Comment by tuxerrante** [comment]
I understand it is on a dead end track but I'm ok with becoming its
godfather, it's a good opportunity to deepen my knowledge with docker and
automation.
Maybe I will search for you again when I'll switch to k8s :)

Should I push only the minor fixes or my entire new project based on yours?

Thanks

Il Mar 24 Set 2019, 10:42 Viktor Farcic <notifications@github.com> ha
scritto:

**Comment by vfarcic** [comment]
Make a PR of whatever you feel more comfortable with and we'll take it from there :)
